extends Node
const GameLogger := preload("res://scripts/core/game_logger.gd")

func _ready() -> void:
	TemplateEngine.register_handler(&"DIRECT_DAMAGE", T01DirectDamage.handle)
	TemplateEngine.register_handler(&"HARD_REMOVAL", T02HardRemoval.handle)
	TemplateEngine.register_handler(&"BOUNCE", T03Bounce.handle)
	TemplateEngine.register_handler(&"COUNTERMAGIC", T04Countermagic.handle)
	TemplateEngine.register_handler(&"COMBAT_TRICK", T05CombatTrick.handle)
	TemplateEngine.register_handler(&"DEBUFF_CONTROL", T06DebuffControl.handle)
	TemplateEngine.register_handler(&"SPELL_DRAW", T07SpellDraw.handle)
	TemplateEngine.register_handler(&"MANA_RAMP", T08ManaRamp.handle)
	TemplateEngine.register_handler(&"TOKEN_GENERATION", T09TokenGeneration.handle)
	TemplateEngine.register_handler(&"RELIC_INTERACTION", T10RelicInteraction.handle)
	TemplateEngine.register_handler(&"KEYWORD_BUFF", T11KeywordBuff.handle)
	TemplateEngine.register_handler(&"CHOICE_CYCLE", T12ChoiceCycle.handle)
	TemplateEngine.register_handler(&"TOUCH_CYCLE", T13TouchCycle.handle)
	TemplateEngine.register_handler(&"DISPLAY_CYCLE", T14DisplayCycle.handle)
	TemplateEngine.register_handler(&"DISPEL_DRAW", T15DispelDraw.handle)
	TemplateEngine.register_handler(&"MARKET_NICHE", T16MarketNiche.handle)
	TemplateEngine.register_handler(&"HEAL_CLEAR", T17HealClear.handle)
	TemplateEngine.register_handler(&"REVIVE", T18Revive.handle)
	TemplateEngine.register_handler(&"PORTAL", T19Portal.handle)
	GameLogger.info("19 template handlers registered", "Templates")
