class_name TerrainAtlasMap
## AUTOGENERATED by tileset_builder.gd v4 — do not edit
const SOURCE_ID := 0
const OBJECT_SOURCE_ID := 1
const CENTER_COORDS := {
	0: Vector2i(0, 0),
	1: Vector2i(6, 0),
	2: Vector2i(46, 0),
	3: Vector2i(47, 0),
	4: Vector2i(48, 0),
	5: Vector2i(49, 0),
	6: Vector2i(55, 0),
}
const VARIANTS := {
	0: [
		Vector2i(1, 0),
		Vector2i(2, 0),
		Vector2i(3, 0),
		Vector2i(4, 0),
		Vector2i(5, 0),
	],
	1: [
		Vector2i(7, 0),
		Vector2i(8, 0),
		Vector2i(9, 0),
		Vector2i(10, 0),
		Vector2i(11, 0),
		Vector2i(12, 0),
		Vector2i(13, 0),
		Vector2i(14, 0),
		Vector2i(15, 0),
		Vector2i(16, 0),
		Vector2i(17, 0),
		Vector2i(18, 0),
		Vector2i(19, 0),
		Vector2i(20, 0),
		Vector2i(21, 0),
		Vector2i(22, 0),
		Vector2i(23, 0),
		Vector2i(24, 0),
		Vector2i(25, 0),
		Vector2i(26, 0),
		Vector2i(27, 0),
		Vector2i(28, 0),
		Vector2i(29, 0),
		Vector2i(30, 0),
		Vector2i(31, 0),
		Vector2i(32, 0),
		Vector2i(33, 0),
		Vector2i(34, 0),
		Vector2i(35, 0),
		Vector2i(36, 0),
		Vector2i(37, 0),
		Vector2i(38, 0),
		Vector2i(39, 0),
		Vector2i(40, 0),
		Vector2i(41, 0),
		Vector2i(42, 0),
		Vector2i(43, 0),
		Vector2i(44, 0),
		Vector2i(45, 0),
	],
	2: [
	],
	3: [
	],
	4: [
	],
	5: [
		Vector2i(50, 0),
		Vector2i(51, 0),
		Vector2i(52, 0),
		Vector2i(53, 0),
		Vector2i(54, 0),
	],
	6: [
	],
}
const DECOR_COORDS := {
	0: [
		{"coords": Vector2i(0, 0), "probability": 0.15},
		{"coords": Vector2i(1, 0), "probability": 0.15},
		{"coords": Vector2i(2, 0), "probability": 0.15},
		{"coords": Vector2i(3, 0), "probability": 0.15},
		{"coords": Vector2i(4, 0), "probability": 0.15},
		{"coords": Vector2i(5, 0), "probability": 0.15},
		{"coords": Vector2i(6, 0), "probability": 0.15},
		{"coords": Vector2i(7, 0), "probability": 0.15},
		{"coords": Vector2i(8, 0), "probability": 0.15},
		{"coords": Vector2i(9, 0), "probability": 0.15},
		{"coords": Vector2i(10, 0), "probability": 0.15},
		{"coords": Vector2i(11, 0), "probability": 0.15},
		{"coords": Vector2i(12, 0), "probability": 0.15},
		{"coords": Vector2i(13, 0), "probability": 0.15},
	],
	1: [
	],
	2: [
	],
	3: [
	],
	4: [
	],
	5: [
	],
	6: [
		{"coords": Vector2i(14, 0), "probability": 0.15},
		{"coords": Vector2i(15, 0), "probability": 0.15},
		{"coords": Vector2i(16, 0), "probability": 0.15},
		{"coords": Vector2i(17, 0), "probability": 0.15},
		{"coords": Vector2i(18, 0), "probability": 0.15},
		{"coords": Vector2i(19, 0), "probability": 0.15},
		{"coords": Vector2i(20, 0), "probability": 0.15},
		{"coords": Vector2i(21, 0), "probability": 0.15},
		{"coords": Vector2i(22, 0), "probability": 0.15},
		{"coords": Vector2i(23, 0), "probability": 0.15},
		{"coords": Vector2i(24, 0), "probability": 0.15},
		{"coords": Vector2i(25, 0), "probability": 0.15},
		{"coords": Vector2i(26, 0), "probability": 0.15},
		{"coords": Vector2i(27, 0), "probability": 0.15},
		{"coords": Vector2i(28, 0), "probability": 0.15},
		{"coords": Vector2i(29, 0), "probability": 0.15},
		{"coords": Vector2i(30, 0), "probability": 0.15},
		{"coords": Vector2i(31, 0), "probability": 0.15},
	],
}
const RIVER_COORDS := []
