class_name TerrainAtlasMap
## AUTOGENERATED by tileset_builder.gd - do not edit
const SOURCE_ID := 0
const CENTER_COORDS := {
	0: Vector2i(1, 0),
	1: Vector2i(2, 0),
	2: Vector2i(3, 0),
	3: Vector2i(5, 0),
	4: Vector2i(8, 0),
	5: Vector2i(9, 0),
	6: Vector2i(12, 0),
}
const DECOR_COORDS := {
}
const RIVER_COORDS := [
	Vector2i(13, 0),
	Vector2i(14, 0),
	Vector2i(15, 0),
	Vector2i(16, 0),
	Vector2i(17, 0),
]
const VARIANTS := {
	0: [
	],
	1: [
	],
	2: [
	],
	3: [
	],
	4: [
	],
	5: [
	],
	6: [
	],
}
