class_name TerrainAtlasMap
## AUTOGENERATED by tileset_builder.gd - do not edit
const SOURCE_ID := 0
const CENTER_COORDS := {
	0: Vector2i(1, 0),
	1: Vector2i(2, 0),
	2: Vector2i(4, 0),
	3: Vector2i(7, 0),
	4: Vector2i(8, 0),
	5: Vector2i(11, 0),
}
const DECOR_COORDS := {
}
const RIVER_COORDS := [
	Vector2i(12, 0),
	Vector2i(13, 0),
	Vector2i(14, 0),
	Vector2i(15, 0),
	Vector2i(16, 0),
]
